version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: bundle update
          command: |
            sudo gem install bundler:2.1.2
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: |
            DISABLE_SPRING=true bundle exec rails test