@startuml engineer

entity "Engineers" as engineer {
  +id  [PK]
  --
  e-mail [string]
  password [string]
  phone_number [string]
  name [string]
  birthday [date]
  sex [integer]
}

note top
  **Association**
  --
  has_many :engineer_skills
  has_many :skills, through: :engineer_skills
  has_many :matchings
  has_many :companies, through: :matchings
  has_many :messages
end note

@enduml